# -*- coding: utf-8 -*-
"""Day_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcmVfkkslgCan737Why8QCtCBY29yIRz
"""

# Read a full line of input from stdin and save it to our dynamically typed variable, input_string.
input_string = input()

# Print a string literal saying "Hello, World." to stdout.
print("Hello, World.")

# TODO: Write a line of code here that prints the contents of input_string to stdout.

print(input_string)